### ISSUE TITLE
请问虚拟滚动下过滤节点功能可用么

### ISSUE THREAD

**Issue by winkying** [wchbrad/vue-easy-tree#1]
请问虚拟滚动下过滤节点功能可用么

**Comment by wchbrad** [comment]
可用的，用法和element组件一致，只是需要注意的是，大数据量下过滤节点会导致界面卡住，建议不要输入时实时过滤
后面会把这个考虑作为优化的点

**Comment by winkying** [comment]
![image](https://user-images.githubusercontent.com/8393930/143820342-88ff0575-fcb5-479b-b421-76175abb5497.png)

**Comment by winkying** [comment]
编译报错。

**Comment by wchbrad** [comment]
初步判断是babel缺少jsx语法的配置，报错的这块用了jsx的语法，根目录下如果有babel.config.js文件，可以增加
`module.exports = {
    presets: [
        '@vue/cli-plugin-babel/preset'
    ]
}`

**Comment by winkying** [comment]
我看了这个代码和https://femessage.github.io/element/#/zh-CN/component/tree 这个是一样的，它这个在虚拟滚动下启用filter过滤功能就只能显示当前视图内的节点，不知道是不是filter方法改变节点的visible属性，但是 visibleList 对象没有监听到变化导致的

**Comment by wchbrad** [comment]
看了下，我跟他在虚拟滚动的底层实现上采用了不同的插件，目前我这边的组件是支持虚拟滚动下的节点过滤、拖拽和懒加载的。
如果编译报错的问题解决了，可以尝试下我这个代码，虚拟滚动下的节点过滤demo：
`<template>
  <div class="ve-tree" style="height: 100%">
    <input placeholder="输入关键字进行过滤" @input="inputFunc" />
    <vue-easy-tree
      ref="veTree"
      node-key="id"
      height="calc(100vh - 30px)"
      :data="treeData"
      :props="props"
      :filter-node-method="filterNode"
    ></vue-easy-tree>
  </div>
</template>

<script>
export default {
  data() {
    return {
      filterText: "",
      props: {
        label: "name",
        children: "children",
      },
      treeData: [],
    };
  },
  watch: {
    filterText(val) {
      this.$refs.veTree.filter(val);
    },
  },
  methods: {
    inputFunc(e) {
      this.filterText = e.target.value;
    },
    filterNode(value, data) {
      if (!value) return true;
      return data.name.indexOf(value) !== -1;
    },
  },
  created() {
    const data = [],
      root = 8,
      children = 3,
      base = 1000;
    for (let i = 0; i < root; i++) {
      data.push({
        id: `${i}`,
        name: `test-${i}`,
        children: [],
      });
      for (let j = 0; j < children; j++) {
        data[i].children.push({
          id: `${i}-${j}`,
          name: `test-${i}-${j}`,
          children: [],
        });
        for (let k = 0; k < base; k++) {
          data[i].children[j].children.push({
            id: `${i}-${j}-${k}`,
            name: `test-${i}-${j}-${k}`,
          });
        }
      }
    }
    this.treeData = data;
  },
};
</script>`

**Comment by wchbrad** [comment]
看了下，我跟他在虚拟滚动的底层实现上采用了不同的插件，目前我这边的组件是支持虚拟滚动下的节点过滤、拖拽和懒加载的。
如果编译报错的问题解决了，可以尝试下我这个代码，虚拟滚动下的节点过滤demo（下载后改成 .vue 后缀）
[demo.txt](https://github.com/wchbrad/vue-easy-tree/files/7616983/demo.txt)

**Comment by winkying** [comment]
![image](https://user-images.githubusercontent.com/8393930/143882244-e23865a8-bb6e-4048-a187-51066bf4a4cb.png)
谢谢大佬，大佬牛逼，确实可以了，找了一天的插件都卡顿，你的这个很丝滑，青出于蓝而胜于蓝

**Comment by wchbrad** [comment]
客气了，互相帮助、互相学习也是开源的意义了，你这么晚才休息也不容易 : )

**Comment by lys748915881** [comment]
当前2层只高亮，第三层才过滤，把过滤节点移到可视区域外，过滤完再滑回来就会出现过滤失效
