### ISSUE TITLE
是否可以支持滚动到指定的树节点

### ISSUE THREAD

**Issue by codecomeon** [wchbrad/vue-easy-tree#13]

**Comment by wchbrad** [comment]
支持的，由于依赖的插件`vue-virtual-scroller`更新，本组件需要同步升级才能使用滚动到指定树节点
供参考：
`<template>
  <div class="ve-tree">
    <button @click="scrollToTarget">scroll</button>
    <vue-easy-tree
      ref="veTree"
      node-key="id"
      height="calc(100vh - 40px)"
      :data="treeData"
      :props="props"
      show-checkbox
    >
    </vue-easy-tree>
  </div>
</template>

<script>
export default {
  data() {
    return {
      props: {
        label: "name",
        children: "children",
      },
      treeData: [],
    };
  },
  methods: {
    scrollToTarget() {
      const virtualInstance = this.$refs["veTree"].$children[0];
      // 自动将目标item滚动到顶部
      const index = virtualInstance.items.findIndex((e) => {
        return e.key === "873";
      });
      this.$nextTick(() => {
        virtualInstance.scrollToItem(index);
      });
    },
  },
  created() {
    const data = [],
      root = 1000,
      children = 2,
      base = 3;
    for (let i = 0; i < root; i++) {
      data.push({
        id: `${i}`,
        name: `test-${i}`,
        children: [],
      });
      for (let j = 0; j < children; j++) {
        data[i].children.push({
          id: `${i}-${j}`,
          name: `test-${i}-${j}`,
          children: [],
        });
        for (let k = 0; k < base; k++) {
          data[i].children[j].children.push({
            id: `${i}-${j}-${k}`,
            name: `test-${i}-${j}-${k}`,
          });
        }
      }
    }
    this.treeData = data;
  },
};
</script>
`
效果：
![动画](https://user-images.githubusercontent.com/48350353/224650396-f17b9efe-7e66-40ba-a19a-733ecf084508.gif)
