### ISSUE TITLE
npm下载包有问题，项目引用文件报找不到对应模块。

### ISSUE THREAD

**Issue by gongxiansheng** [wchbrad/vue-easy-tree#17]
`package.json`里面的 main: './dist/***',没有对应文件呢

**Comment by wchbrad** [comment]
如果是npm下载的，并没有对应文件，但不影响在项目中引用：
全局引用：
import Vue from "vue";
import VueEasyTree from "@wchbrad/vue-easy-tree";
// 样式文件，可以根据需要自定义样式或主题
import "@wchbrad/vue-easy-tree/src/assets/index.scss"
Vue.use(VueEasyTree)

组件内引用：
import VueEasyTree from "@wchbrad/vue-easy-tree";
// 样式文件，可以根据需要自定义样式或主题
import "@wchbrad/vue-easy-tree/src/assets/index.scss"

export default {
  components: {
    VueEasyTree
  }
}

**Comment by wchbrad** [comment]
现在已经增加了/dist目录
