### ISSUE TITLE
启用虚拟滚动，自动滚动到选中的节点位置

### ISSUE THREAD

**Issue by 361so** [wchbrad/vue-easy-tree#24]
启用虚拟滚动后，div中只有当前可视范围内的20几条数据，该如何通过外部点击使一个节点选中并且滚动到这个节点处呢？

**Comment by 361so** [comment]
目前采用将外部指定的节点名称当作关键词搜索。

**Comment by 361so** [comment]
请问.scrollToItem()有用吗？ 在 #13 中我看示例中有，但是我写了没有作用

**Comment by wchbrad** [comment]
升级到v1.0.11版本，使用类似`this.$refs["veTree"].setChecked(key,true)`和`this.$refs["veTree"].scrollToItem(key)`的方式滚动到目标节点。注意：如果目标节点是子节点，需要自己处理展开

**Comment by 361so** [comment]
> 升级到v1.0.11版本，使用类似`this.$refs["veTree"].setChecked(key,true)`和`this.$refs["veTree"].scrollToItem(key)`的方式滚动到目标节点。注意：如果目标节点是子节点，需要自己处理展开

已更新处理，谢谢！另还请麻烦尽快更新至CNPM

**Comment by wchbrad** [comment]
客气了

**Comment by long111321** [comment]
可以使选中的节点滚动到树列表的中间位置吗？ 或者说，可以自动通过设置的方法自动调整树的滚动吗（比如点击某个按钮，滚动条自动向下滚动50像素的距离）

**Comment by long111321** [comment]
谢谢，很完美
