### ISSUE TITLE
根据data中的属性，隐藏checkbox

### ISSUE THREAD

**Issue by hu2014** [wchbrad/vue-easy-tree#25]
大佬，我想实现根据数据中的某个属性，决定是否展示checkbox，怎么弄啊。比如图片中，不想要通道的checkbo展示出来。这个树的层级不定，可能会嵌套很深。
![image](https://user-images.githubusercontent.com/36222808/229448845-ea5082f3-06b4-4237-b451-531b3ac92108.png)

**Comment by wchbrad** [comment]
使用`render-content`自定义内容，check-box根据data属性的需要渲染

**Comment by hu2014** [comment]
那这样生成的checkbox就不能使用定义好的那些方法了吧。比如获取选择的节点



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wchbrad/vue-easy-tree] 根据data中的属性，隐藏checkbox (Issue #25)





 
使用render-content自定义内容，check-box根据data属性的需要渲染

**Comment by wchbrad** [comment]
`check-strictly="true"`可以解决父节点不能选择的问题，但不能全选，可以自己实现checkbox的选中和取消选中方法

**Comment by hu2014** [comment]
有指定更新某个节点的方法吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月4日(星期二) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wchbrad/vue-easy-tree] 根据data中的属性，隐藏checkbox (Issue #25)





 
check-strictly="true"可以解决父节点不能选择的问题，但不能全选，可以自己实现checkbox的选中和取消选中方法

**Comment by hu2014** [comment]
哈哈.对象是同一个对象。可以更改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月4日(星期二) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wchbrad/vue-easy-tree] 根据data中的属性，隐藏checkbox (Issue #25)





 
check-strictly="true"可以解决父节点不能选择的问题，但不能全选，可以自己实现checkbox的选中和取消选中方法
