### ISSUE TITLE
不同的节点可以不一样的高吗？

### ISSUE THREAD

**Issue by long111321** [wchbrad/vue-easy-tree#27]
比如一个树结构，有些节点需要高度大些，有些节点需要高度小些，有属性可以进行这样的调整吗 ？发现有个item-size是可以调节高度的，但他是调整所有节点高度，可以一些特殊的节点去专门调节他的高度吗；如果使用scoped slot的话 只能改样式，但涉及到高度时，超出的部分并不能给高撑开

**Comment by wchbrad** [comment]
不行，variable size会导致virtual tree失去性能

**Comment by long111321** [comment]
好的
