### ISSUE TITLE
这个渲染大数据好像最大只能到10W

### ISSUE THREAD

**Issue by hu2014** [wchbrad/vue-easy-tree#28]
用的虚拟列表组件vue-virtual-scroller，最大支持到67W，但是改造成树形之后，最大只能到10W的数据量，性能差距有点大。

**Comment by wchbrad** [comment]
virtual list和virtual tree是有区别的，主要包括，dom结构上不完全一致；virtual list没有隐藏展开这些逻辑。
或者你有想法欢迎提pr

**Comment by hu2014** [comment]
额。这样啊。我瞅瞅看。按道理来说100W的计算量完全没问题的，或许这个基础虚拟滚动组件就有问题
