### ISSUE TITLE
节点连接线？

### ISSUE THREAD

**Issue by WaitingforPu** [wchbrad/vue-easy-tree#29]
![iss](https://user-images.githubusercontent.com/26001471/231932980-c4b7f654-93c4-41df-bb88-66dd4bec252f.png)

**Comment by WaitingforPu** [comment]
如果您有时间可以帮忙看看

**Comment by wchbrad** [comment]
样式指节点之间带连接线？

**Comment by WaitingforPu** [comment]
> 样式指节点之间带连接线？

是的 就是想问问这里的样式如果写呢。感觉还是挺复杂的 要考虑缩进和线条

**Comment by wchbrad** [comment]
如果是使用virtula tree，目前不支持这种样式，virtula tree每行都是一个item，但并没有层级包含关系，无法创建有包含或归属关系的缩进和线条

**Comment by WaitingforPu** [comment]
谢谢您的回复呢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wchbrad/vue-easy-tree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wchbrad/vue-easy-tree] 你好呀。目前使用组件有个样式问题想咨询一下。如图所示 (Issue #29)





 
如果是使用virtula tree，目前不支持这种样式，virtula tree每行都是一个item，但并没有层级包含关系，无法创建有包含或归属关系的缩进和线条
