### ISSUE TITLE
列表滚动过程引起部分treeitem 消失

### ISSUE THREAD

**Issue by qylibohao** [wchbrad/vue-easy-tree#30]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/5283516/233251391-1ca95375-ebe7-4426-8f11-f4fa009b88f8.png">
<img width="321" alt="image" src="https://user-images.githubusercontent.com/5283516/233251551-b808546f-711d-4ed1-8fd0-83bef3042370.png">
一层一层暂开的时候会出现某项消失问题，
滚动距离够的话后是有可能又对了的

**Comment by qylibohao** [comment]
已解决

**Comment by lzyllp** [comment]
> 已解决

怎么解决的？

**Comment by lzyllp** [comment]
> 已解决

怎么解决的
