### ISSUE TITLE
为什么高度谁为100%虚拟滚动不生效呢

### ISSUE THREAD

**Issue by Dnxbhhz** [wchbrad/vue-easy-tree#34]

**Comment by wchbrad** [comment]
100%不是有效的绝对像素单位，需要使用px或者calc(100vh - 10px)转换。虚拟滚动需要用到绝对单位计算应该展示多少个item等数据

**Comment by Dnxbhhz** [comment]
> 100%不是有效的绝对像素单位，需要使用px或者calc(100vh - 10px)转换。虚拟滚动需要用到绝对单位计算应该展示多少个item等数据

改成calc就可以了，谢谢
