### ISSUE TITLE
为什么自定义的节点内容 样式错乱了  translateY(26px) 一直是26px

### ISSUE THREAD

**Issue by hbtj1759** [wchbrad/vue-easy-tree#35]

**Comment by wchbrad** [comment]
自定义的每个节点都是固定高度么？

**Comment by hbtj1759** [comment]
是啊

**Comment by hbtj1759** [comment]
我设置的是固定40px的高度

**Comment by wchbrad** [comment]
itemSize属性改成40，默认是26的

**Comment by hbtj1759** [comment]
感谢大佬，可以了   配置项说明在哪里啊，我一直没看到

**Comment by wchbrad** [comment]
https://github.com/wchbrad/vue-easy-tree/blob/main/element-ui-tree.zh-CN.md
![image](https://github.com/wchbrad/vue-easy-tree/assets/48350353/494607c7-899e-4bc9-b073-8dc1b8e004b3)

**Comment by hbtj1759** [comment]
好的 感谢感谢
