### ISSUE TITLE
:render-after-expand="false"设置无效

### ISSUE THREAD

**Issue by weixiaoxiang** [wchbrad/vue-easy-tree#38]
如题，设置:render-after-expand="false"后，点击父节点，子节点并未触发 @check-change

**Comment by wchbrad** [comment]
在虚拟滚定下，目前确实存在这个问题。
但是如果你想在未展开子节点时，点击父节点，拿到所有已勾选的节点（包括子节点），可以在 @check-change中使用this.$refs["veTree"].getCheckedNodes()或this.$refs["veTree"].getCheckedKeys()拿到已选择的节点数组或者节点key数组。veTree指的是vue-easy-tree的ref实例
