### ISSUE TITLE
滚动到底部渲染速度慢

### ISSUE THREAD

**Issue by qishibo** [wchbrad/vue-easy-tree#4]
正要实现虚拟滚动，就找到你这个了，赞
不过跑了demo，发现最顶端的渲染延迟可忽略，但几万节点时，最底端的节点渲染会有延迟，卡顿了几下，是因为上面节点太多，累计计算的原因么【展开节点2w】
![Peek 2022-04-05 11-03](https://user-images.githubusercontent.com/5136418/161670757-e3e8919d-6a34-4511-81e0-118769b94d9d.gif)

**Comment by qishibo** [comment]
ps: 顶部也是如此
![Peek 2022-04-05 11-18](https://user-images.githubusercontent.com/5136418/161672219-5c3ec15b-d01c-4424-98c5-743e46c27a65.gif)

**Comment by wchbrad** [comment]
感谢使用，按照你这里的演示，已复现并修复了。现在item重用时，会移除多余未重用的组件。

**Comment by wchbrad** [comment]
npm发布了新的版本1.0.7

**Comment by qishibo** [comment]
:100:
