### ISSUE TITLE
在出现滚动条后，向上滚动过程会突然全部收起所有的节点

### ISSUE THREAD

**Issue by zhang382847657** [wchbrad/vue-easy-tree#40]
- **项目描述：** 我原来使用el-tree的updateKeyChildren来实现类似点击某节点后再动态加载该节点下的数据，并没有采用el-tree组件的lazy+load的形式去懒加载，后来某些节点下面会有上万条数据导致页面卡死后，尝试使用vue-easy-tree的虚拟滚动来解决问题

- **问题描述：** 再直接替换el-tree为vue-easy-tree时，没有任何报错，每个节点都能顺利展开，尤其是上万条节点也能顺利显示，但是当出现滚动条时，只要向上滚动至接近顶部时，所有展开的节点会全部收起。

**Comment by wchbrad** [comment]
方便贴一下最小可重现代码么，贴个txt文件也可以

**Comment by wchbrad** [comment]
[demo.txt](https://github.com/wchbrad/vue-easy-tree/files/12881950/demo.txt)
我测试了一个demo：使用虚拟滚动，点击节点A时在A子节点的最后位置动态增加一个节点，并出现滚动条，未复现你的问题
![dh](https://github.com/wchbrad/vue-easy-tree/assets/48350353/9e2740e2-238f-46a7-8c59-3c4b33402b04)
