### ISSUE TITLE
虚拟渲染可以支持横向滚动条吗

### ISSUE THREAD

**Issue by liushuhon** [wchbrad/vue-easy-tree#45]

**Comment by shuzepeng** [comment]
如果子级有选中， 必须点击才可以回显父级半选或选中状态， 这是bug

**Comment by liushuhon** [comment]
> 你指的是节点字符串过长？

是的，如果层级过多的话，字符串过长横向会放不下

**Comment by wchbrad** [comment]
目前横向滚动不支持虚拟滚动，你的问题可以通过下面两个办法解决：
1、增加节点高度，默认高度不能满足要求可以增加，以容纳两行；
2、自定义渲染节点，比如超长的...省略，hover后显示tooltip，注意需要保持节点高度固定
