### ISSUE TITLE
开启虚拟滚动后，当前勾选框的选择状态会同步到其他item的ui上, 数据层面无影响

### ISSUE THREAD

**Issue by kongwy229** [wchbrad/vue-easy-tree#49]
开启虚拟滚动后，手动勾选 1、2、3 的勾选框， 向下划动到18、19、20位置时会发现这三个位置的勾选框初始状态是勾选的，进入视图中立刻就变成未勾选状态（但是肉眼可见这个状态的切换）。
在本地开发环境手动将节点勾选框的key设置后，该bug就会消失。
<img width="484" alt="image" src="https://github.com/wchbrad/vue-easy-tree/assets/27497945/d2c80c4f-3915-43c8-9907-6d97c390dbb2">

希望可以考虑在这里增加key的设置

**Comment by wchbrad** [comment]
感谢提出问题，下个版本会修复此问题
