### ISSUE TITLE
能否加入item-size props来让开发者传入,现在是写死的 有些样式受到限制

### ISSUE THREAD

**Issue by zcx992132258** [wchbrad/vue-easy-tree#6]
![image](https://user-images.githubusercontent.com/54138798/185871584-43af9946-ccfc-41b1-b4cd-b2b30148a9ec.png)
代码里面每行行高写死了 是否写成props来供开发者修改

**Comment by wchbrad** [comment]
可以，我需要测试下，防止引起其他问题
