### ISSUE TITLE
insertAfter 插入节点到根，抛出异常

### ISSUE THREAD

**Issue by axetroy** [wchbrad/vue-easy-tree#7]
![截屏2022-08-31 17 19 17](https://user-images.githubusercontent.com/9758711/187644720-62fdd3ca-2197-4731-ab08-62bcd3c7a734.png)

![截屏2022-08-31 17 20 04](https://user-images.githubusercontent.com/9758711/187644914-e9ded67d-192c-4fcd-ae80-321d23226c4c.png)

对于根节点，有点奇怪

**Comment by axetroy** [comment]
只需要改一改，即可修复

```diff
    getChildren(forceInit = false) {
        // this is data
-        if (this.level === 0) return this.data
+        if (this.level === 0) return this.childNodes.map(v => v.data)
```

**Comment by wchbrad** [comment]
是个可能的问题，感谢修复，我根据你这个测试一下

**Comment by wchbrad** [comment]
你好，我使用 插入节点到根 的insertAfter方法，未发现问题，是否未按照insertAfter的以下所述方法使用而导致的报错？

- (data, refNode) 接收两个参数，1. 要增加的节点的 data 2. 要增加的节点的前一个节点的 data、key 或者 node

附测试gif
![df](https://user-images.githubusercontent.com/48350353/195236695-f076f871-c3a6-4cce-8a9d-42330ecdb543.gif)

如有问题，请提交最小可重现代码，感谢
