### ISSUE TITLE
从隐藏到显示，虚拟列表不生效

### ISSUE THREAD

**Issue by guoqiangui** [wchbrad/vue-easy-tree#8]
我把vue-easy-tree和el-select组合了一下，做成了树型的下拉框组件，展开下拉框的时候虚拟列表不生效，布局也不正确，要不要考虑解决一下这种从隐藏到显示的问题，例如可以向外暴露一个重新渲染的函数

**Comment by guoqiangui** [comment]
![image](https://user-images.githubusercontent.com/45208340/188401746-310890d0-6a0c-42f6-8d54-0c2b24d7acf0.png)

**Comment by wchbrad** [comment]
感谢提出建议，初步看起来会有点困难，直接原因是 el-select的下拉框高度是height: 100%。而目前使用虚拟tree的要求是高度需要定义为更具体的值比如100px，100vh之类，需要再评估下
