### ISSUE TITLE
在节点上增加子组件，子组件包含el-dialog组件时，不展示

### ISSUE THREAD

**Issue by wocswang** [wchbrad/vue-easy-tree#9]
![image](https://user-images.githubusercontent.com/23565529/191469605-599eba0d-b476-4656-990f-9dd8953651a4.png)
子组件里面有弹框组件，当触发点击显示子组件的弹框时，只显示遮罩层，不显示弹框

**Comment by wchbrad** [comment]
TreeRender组件没有详细的代码，但是看起来是这样的问题：弹框组件应该是全局的，放在tree之外，tree内部只渲染tree的label和控制dialog的显示与否，不应把整个dialog都放入tree内部
